c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
c_compiler:  # [not win]
  - clang  # [not win]
c_compiler_version:  # [not win]
  - 18  # [not win]
cxx_compiler:  # [not win]
  - clangxx  # [not win]
c_compiler_version:  # [not win]
  - 18  # [not win]
