{% set name = "kanidm-clients" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kanidm/kanidm/archive/refs/tags/v{{ version.replace("rc", "-rc.") }}.tar.gz
  sha256: 6f53f41075c3090e5100936d9229c301fa5d7cb2ed3a224ebae881fdb873e9df

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
    - openssl
    - libudev  # [linux]
  host:
    - libudev  # [linux]
    - openssl

test:
  commands:
    - kanidm version

about:
  home: https://kanidm.com/
  summary: 'A simple, secure and fast identity management platform'
  description: |
    Kanidm is a simple and secure identity management platform, allowing other applications and services to offload the challenge of authenticating and storing identities to Kanidm.
    The goal of this project is to be a complete identity provider, covering the broadest possible set of requirements and integrations. You should not need any other components (like Keycloak) when you use Kanidm - we already have everything you need!
    To achieve this we rely heavily on strict defaults, simple configuration, and self-healing components. This allows Kanidm to run from small home labs, families, small business, and all the way to the largest enterprise needs.
    If you want to host your own authentication service, then Kanidm is for you!
  license: MIT
  license_family: MOZILLA
  license_file:
    - LICENSE.md
    - THIRDPARTY_LICENSES.yaml
  doc_url: https://kanidm.github.io/kanidm/stable/
  dev_url: https://github.com/kanidm/kanidm

extra:
  recipe-maintainers:
    - freundTech
